
src/cscope			usr/bin
contrib/ocs			usr/bin
contrib/xcscope/cscope-indexer	usr/bin
contrib/README 		        usr/share/doc/cscope/contrib

contrib/webcscope/cgi-lib.pl	usr/share/doc/cscope/contrib/webcscope
contrib/webcscope/cscope	usr/share/doc/cscope/contrib/webcscope
contrib/webcscope/hilite.c	usr/share/doc/cscope/contrib/webcscope
contrib/webcscope/icons		usr/share/doc/cscope/contrib/webcscope
contrib/webcscope/INSTALL	usr/share/doc/cscope/contrib/webcscope
contrib/webcscope/TODO		usr/share/doc/cscope/contrib/webcscope
