.TH cscope-indexer 1 "30. December 2002" "Script to index files for cscope"
.SH NAME
cscope-indexer \- Script to index files for cscope

.SH SYNOPSIS
.B cscope-indexer [\fI-v\fR] [\fI-f database_file\fR] [\fI-i list_file\fR]
[\fI-l\fR] [\fI-r\fR]

.SH DESCRIPTION
This script generates a list of files to index
(cscope.out), which is then (optionally) used to
generate a cscope database.  You can use this script
to just build a list of files, or it can be used to
build a list and database.  This script is not used to
just build a database (skipping the list of files
step), as this can be simply done by just calling
"cscope -b".

Normally, cscope will do its own indexing, but this
script can be used to force indexing.  This is useful
if you need to recurse into subdirectories, or have
many files to index (you can run this script from a
cron job, during the night).  It is especially useful
for large projects, which can contstantly have source
files added and deleted; by using this script, the
changing sources files are automatically handled.

Currently, any paths containing "/CVS/" or "/RCS/" are
stripped out (ignored).

.SH OPTIONS
.TP
.B \-f database_file
Specifies the cscope database file (default: cscope.out).

.TP
.B \-i list_file
Specifies the name of the file into which the list of files
to index is placed (default: cscope.files).

.TP
.B \-l
Suppress the generation/updating of the cscope database
file.  Only a list of files is generated.

.TP
.B \-r
Recurse into subdirectories to locate files to index.
Without this option, only the current directory is
searched.

.TP
.B \-v
Be verbose.  Output simple progress messages.

.SH "SEE ALSO"
.BR cscope (1)

.SH AUTHOR
This manual page was written for the Debian GNU/Linux system by Robert Lemmen
<robertle@semistable.com> (but may be used by others, of course)
